models/Cladr.php
<?php

namespace app\models;

use Yii;
use yii\db\ActiveRecord;


class Cladr extends ActiveRecord
{
    public $code_sent;
    public $code_get;
    public $shipment_height = 0.2;
    public $shipment_width = 0.2;
    public $shipment_length = 1;
    public $pointsent;
    public $pointget;
    public $count_place = 1;
    public $weight_one_place = 1;
    public $type_packaging;
    public $send_shipment;
    public $get_shipment;
    public $value_json;
    public $res;
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'cladr';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['cityID', 'name', 'code', 'searchString', 'regname', 'regcode', 'zonname', 'zoncode'], 'required'],
            [['cityID', 'name', 'code', 'searchString', 'regname', 'regcode', 'zonname', 'zoncode', 'code_sent',
                'code_get', 'shipment_height', 'shipment_width', 'shipment_length', 'pointsent', 'pointget',
                'count_place', 'weight_one_place', 'type_packaging', 'send_shipment', 'get_shipment', 'res', 'value_json'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'cityID' => 'City ID',
            'name' => 'Name',
            'code' => 'Code',
            'searchString' => 'Search String',
            'regname' => 'Regname',
            'regcode' => 'Regcode',
            'zonname' => 'Zonname',
            'zoncode' => 'Zoncode',
            'pointsent' => 'Место отправления',
            'pointget' => 'Место назначения',
            'shipment_height' => 'Высота груза',
            'shipment_width' => 'Ширина груза',
            'shipment_length' => 'Длина груза',
            'count_place' => 'Количество мест',
            'weight_one_place' => 'Масса одного места',
            'type_packaging' => 'Тип упаковки',
            'code_sent' => 'Код места отправления',
            'code_get' => 'Код места получения',
            'send_shipment' => 'Забрать у заказчика',
            'get_shipment' => 'Доставить адресату',
        ];
    }

    public function getShipTypeList()
    {
        return [
            '0x838fc70baeb49b564426b45b1d216c15' => 'Жесткая упаковка',
            '0x951783203a254a05473c43733c20fe72' => 'Картонная коробка',
            '0x9a7f11408f4957d7494570820fcf4549' => 'Дополнительная упаковка',
            '0xa8b42ac5ec921a4d43c0b702c3f1c109' => 'Воздушно-пузырьковая плёнка',
            '0xad22189d098fb9b84eec0043196370d6' => 'Мешок',
        ];
    }

    public function getCityCode($cityname)
    {
       return self::findOne(['name' => $cityname])->code;
    }

    public function sendShipDataList()
    {
        return [
            'true' => 'Забрать у заказчика',
            'false' => 'Отправка с терминала'
        ];
    }

    public function getShipDataList()
    {
        return [
            'true' => 'Доставить адресату',
            'false' => 'Доставка до терминала'
        ];
    }

}

controllers/CladrController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Cladr;
use app\models\CladrSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\db\Query;
use yii\web\Response;
use linslin\yii2\curl;

/**
 * CladrController implements the CRUD actions for Cladr model.
 */
class CladrController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Cladr models.
     * @return mixed
     */
    public function actionIndex()
    {

        $model = new Cladr();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id, 'name' => $model->name, 'searchString' => $model->searchString, 'regname' => $model->regname]);
        }
        if (!empty($model->pointsent) & !empty($model->pointget)) {
            $model->code_sent = $model->getCityCode($model->pointsent);
            $model->code_get = $model->getCityCode($model->pointget);
        }
        if (empty($model->pointsent) & empty($model->pointget)) {
            $request = Yii::$app->request;
            $model->code_sent = $request->get('from');
            $model->code_get = $request->get('to');
        }
        if (empty($model->send_shipment) & empty($model->get_shipment)){
            $model->send_shipment = true;
            $model->get_shipment = true;
        }
        if (empty($model->type_packaging)){
            $model->type_packaging = '0xad22189d098fb9b84eec0043196370d6';
        }

        $value = [
            'derivalPoint' => $model->code_sent,
            'arrivalPoint' => $model->code_get,
            'length' => $model->shipment_length,
            'width' => $model->shipment_width,
            'height' => $model->shipment_height,
            'count_place' => $model->count_place,
            'weight_one_place' => $model->weight_one_place,
            'packages' => $model->type_packaging,
            'derivalDoor' => $model->send_shipment,
            'arrivalDoor' => $model->get_shipment,
        ];
        $model->value_json = json_encode($value, true);

        return $this->render('index', [
            'model' => $model,
        ]);
    }

    /**
     * Displays a single Cladr model.
     * @param integer $id
     * @param string $name
     * @param string $searchString
     * @param string $regname
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id, $name, $searchString, $regname)
    {
        return $this->render('view', [
            'model' => $this->findModel($id, $name, $searchString, $regname),
        ]);
    }

    /**
     * Creates a new Cladr model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {

        $model = new Cladr();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id, 'name' => $model->name, 'searchString' => $model->searchString, 'regname' => $model->regname]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);

    }

    /**
     * Updates an existing Cladr model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @param string $name
     * @param string $searchString
     * @param string $regname
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id, $name, $searchString, $regname)
    {
        $model = $this->findModel($id, $name, $searchString, $regname);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id, 'name' => $model->name, 'searchString' => $model->searchString, 'regname' => $model->regname]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Cladr model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @param string $name
     * @param string $searchString
     * @param string $regname
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id, $name, $searchString, $regname)
    {
        $this->findModel($id, $name, $searchString, $regname)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Cladr model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @param string $name
     * @param string $searchString
     * @param string $regname
     * @return Cladr the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id, $name, $searchString, $regname)
    {
        if (($model = Cladr::findOne(['id' => $id, 'name' => $name, 'searchString' => $searchString, 'regname' => $regname])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

    public function actionCitylist($q = null, $id = null)
    {
        Yii::$app->response->format = Response::FORMAT_JSON;

        $out = ['results' => ['id' => '', 'text' => '']];

        if (!is_null($q)) {
            $query = new Query();
            $query->select('name AS id, code AS text')
                ->from('cladr')
                ->where(['like', 'name', $q])
                ->limit(10);
            $command = $query->createCommand();
            $data = $command->queryAll();
            $out['results'] = array_values($data);
        } elseif ($id > 0) {
            $out['results'] = ['id' => $id, 'text' => Cladr::findOne($id)->name];
        }

        return $out;
    }

    public function actionCalc()
    {

        $model = new Cladr();

        Yii::$app->response->format = Response::FORMAT_JSON;

        $request = Yii::$app->request;

        if (!empty($request->get())) {
            $result = json_decode($request->get('value', true));
        }

        $sizedWeight = $result->count_place * $result->weight_one_place;
        $sizedVolume = str_replace(',', '.', $result->length) * str_replace(',', '.', $result->width) * str_replace(',', '.', $result->height);
        $params = [
            'appkey' => 'F3B342E4-B256-4008-B8C0-665D8F784714',
            'sessionID' => 'D8C07080-3DD8-47E9-B66C-A1E64BB64CC2',
            'derivalPoint' => $result->derivalPoint,
            'arrivalPoint' => $result->arrivalPoint,
            'derivalDoor' => $result->derivalDoor,
            'arrivalDoor' => $result->arrivalDoor,
            'sizedVolume' => $sizedVolume,
            'sizedWeight' => $sizedWeight,
            'oversizedVolume' => '0',
            'oversizedWeight' => '0',
            'length' => str_replace(',', '.', $result->length),
            'width' => str_replace(',', '.', $result->width),
            'height' => str_replace(',', '.', $result->height),
            //'freight_uid' => 'false',
            'statedValue' => '1000',
            'packages' => $result->packages,
        ];
        $curl = new curl\Curl();

        return $model->res = json_decode($curl->setRequestBody(json_encode($params))
            ->setHeaders([
                'Content-Type' => 'application/json',
                'Content-Length' => strlen(json_encode($params))
            ])
            ->post('https://api.dellin.ru/v1/public/calculator.json'), true);

    }
}

views/cladr/_form.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;
use kartik\select2\Select2;
use yii\web\JsExpression;

?>

<?php $form = ActiveForm::begin(); ?>

<div class="container">
    <div class="row">

        <div class="col-sm-6">
            <?php
            echo $form->field($model, 'pointsent')->widget(Select2::classname(), [
                'options' => ['placeholder' => 'Поиск города ...'],
                'pluginOptions' => [
                    'allowClear' => true,
                    'minimumInputLength' => 3,
                    'language' => [
                        'errorLoading' => new JsExpression("function () { return 'Поиск...'; }"),
                    ],
                    'ajax' => [
                        'url' => Url::to('/cladr/citylist'),
                        'dataType' => 'json',
                        'data' => new JsExpression('function(params) { return {q:params.term}; }')
                    ],
                    'escapeMarkup' => new JsExpression('function (markup) { return markup; }'),
                    'templateResult' => new JsExpression('function (cladr) { return cladr.id; }'),
                    'templateSelection' => new JsExpression('function (cladr) { return cladr.id; }'),
                ],
            ]);

            ?>
        </div>


        <div class="col-sm-6">

            <?php
            echo $form->field($model, 'pointget')->widget(Select2::classname(), [
                'options' => ['placeholder' => 'Поиск города ...'],
                'pluginOptions' => [
                    'allowClear' => true,
                    'minimumInputLength' => 3,
                    'language' => [
                        'errorLoading' => new JsExpression("function () { return 'Поиск...'; }"),
                    ],
                    'ajax' => [
                        'url' => Url::to('/cladr/citylist'),
                        'dataType' => 'json',
                        'data' => new JsExpression('function(params) { return {q:params.term}; }')
                    ],
                    'escapeMarkup' => new JsExpression('function (markup) { return markup; }'),
                    'templateResult' => new JsExpression('function (cladr) { return cladr.id; }'),
                    'templateSelection' => new JsExpression('function (cladr) { return cladr.id; }'),
                ],
            ]);

            ?>

        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-sm-4">

            <?= $form->field($model, 'shipment_height')->textInput(['maxlength' => true]) ?>
        </div>
        <div class="col-sm-4">
            <?= $form->field($model, 'shipment_width')->textInput(['maxlength' => true]) ?>
        </div>
        <div class="col-sm-4">
            <?= $form->field($model, 'shipment_length')->textInput(['maxlength' => true]) ?>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-sm-4">
            <?= $form->field($model, 'count_place')->textInput(['maxlength' => true]) ?>
        </div>
        <div class="col-sm-4">
            <?= $form->field($model, 'weight_one_place')->textInput(['maxlength' => true]) ?>
        </div>

    </div>
</div>

    <div class="container">
        <div class="row">
            <div class="col-sm-4">
                <?= $form->field($model, 'send_shipment')->dropDownList($model->sendShipDataList()) ?>
            </div>
            <div class="col-sm-4">
                <?= $form->field($model, 'get_shipment')->dropDownList($model->getShipDataList()) ?>
            </div>
        </div>
    </div>

<div class="container">
    <div class="row">
        <div class="col-sm-3">
        <?= $form->field($model, 'type_packaging')->dropDownList($model->getShipTypeList()) ?>
    </div>
    </div>
</div>

<div class="form-group">
    <?= Html::submitButton('Узнать стоимость', ['class' => 'btn btn-success']) ?>
</div>

<?php ActiveForm::end(); ?>


<?php
//var_dump($model->res);

views/cladr/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\CladrSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="cladr-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'cityID') ?>

    <?= $form->field($model, 'name') ?>

    <?= $form->field($model, 'code') ?>

    <?= $form->field($model, 'searchString') ?>

    <?php // echo $form->field($model, 'regname') ?>

    <?php // echo $form->field($model, 'regcode') ?>

    <?php // echo $form->field($model, 'zonname') ?>

    <?php // echo $form->field($model, 'zoncode') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/cladr/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Cladr */

$this->title = 'Расчет стоимости доставки';
//$this->params['breadcrumbs'][] = ['label' => 'Cladrs', 'url' => ['index']];
//$this->params['breadcrumbs'][] = $this->title;
?>


<h1><?= Html::encode($this->title) ?></h1>

<?= $this->render('_form', [
    'model' => $model,
]) ?>
<?php
var_dump($model);
?>

<img src="/img/18306_edb06c582bc768d408e4d2fd57e3404c.jpg" alt="">
<div class="order-index">
    <div class="box box-default">
        <div class="box-body">
            <div data-spy="scroll" data-target="#navbar-example" data-offset="0"
                 style="height:auto;overflow:auto; position: relative; border: padding: 10px;">
                <div id="api">
                    <h4>Отправление из:</h4>
                    <div id="data-derival-city"><img src="/img/loading.gif" alt="" width="200"></div>
                    <h4>Адреса терминалов отправки:</h4>
                    <div id="data-derival-terminals"></div>
                    <h4>Доставка в:</h4>
                    <div id="data-arrrival-city"></div>
                    <h4>Адреса терминалов доставки:</h4>
                    <div id="data-arrival-terminals"></div>
                    <h4>Данные межтерминальной доставки:</h4>
                    <div id="data-price"></div>
                    <strong>Дата отправки из ОСП-отправителя: </strong>
                    <div id="data-order_dates-derrival_from_osp_sender"></div>
                    <strong>Дата прибытия в ОСП-получатель: </strong>
                    <div id="data-order_dates-arrival_to_osp_receiver"></div>
                    <strong>Срок доставки груза: </strong>
                    <div id="data-time-value"></div>
                </div>
            </div>
        </div>
    </div>
</div>


<script type="text/javascript">
    var str = location.href;
    //  var arr = str.split('/');
    //  + arr['5']
    $.ajax({
        url: '/cladr/calc/?from=1000000100000000000000000&to=100000100700000000000000',
        dataType: 'json',
        error: function () {
            $("#api").html('Ошибка, попробуйте еще раз или обратитесь к администратору');
        },
        success: function (data) {
            console.log(data);
            if (data.errors != null) {
                $("#api").html(data.errors.messages[0]);
            }
            $("#data-derival-city").html(data.derival.city);
            $.each(data.derival.terminals, function () {
                $('#data-derival-terminals').append(this.address + '<br>');
            });
            $("#data-arrrival-city").html(data.arrival.city);
            $.each(data.arrival.terminals, function () {
                $('#data-arrival-terminals').append(this.address + '<br>');
            });
            $("#data-price").html(data.price);
            $("#data-air-price").html(data.price);
            $("#data-time-value").html(data.time.nominative);
            $("#data-order_dates-derrival_from_osp_sender").html(data.order_dates.derrival_from_osp_sender);
            $("#data-order_dates-arrival_to_osp_receiver").html(data.order_dates.arrival_to_osp_receiver);
        }
    });
</script>

views/cladr/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\CladrSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Cladrs';

?>


<h1>Расчет стоимости доставки</h1>


<?= $this->render('_form', [
    'model' => $model,
]) ?>

<img src="/img/18306_edb06c582bc768d408e4d2fd57e3404c.jpg" alt="">
<div class="order-index">
    <div class="box box-default">
        <div class="box-body">
            <div data-spy="scroll" data-target="#navbar-example" data-offset="0"
                 style="height:auto;overflow:auto; position: relative; border: padding: 10px;">
                <div id="api">
                    <h4>Отправление из:</h4>
                    <div id="data-derival-city"><img src="/img/loading.gif" alt="" width="200"></div>
                    <h4>Адреса терминалов отправки:</h4>
                    <div id="data-derival-terminals"></div>
                    <h4>Доставка в:</h4>
                    <div id="data-arrrival-city"></div>
                    <h4>Адреса терминалов доставки:</h4>
                    <div id="data-arrival-terminals"></div>
                    <h4>Данные межтерминальной доставки:</h4>
                    <div id="data-price"></div>
                    <strong>Дата отправки из ОСП-отправителя: </strong>
                    <div id="data-order_dates-derrival_from_osp_sender"></div>
                    <strong>Дата прибытия в ОСП-получатель: </strong>
                    <div id="data-order_dates-arrival_to_osp_receiver"></div>
                    <strong>Срок доставки груза: </strong>
                    <div id="data-time-value"></div>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    var str = location.href;
    //  var arr = str.split('/');
    //  + arr['5']
    $.ajax({
        url: '/cladr/calc/?value=<?php echo $model->value_json ?>',
        dataType: 'json',
         error: function () {
            $("#api").html('Ошибка, попробуйте еще раз или обратитесь к администратору');
        },
        success: function (data) {
            console.log(data);
            if (data.errors != null) {
                $("#api").html(data.errors.messages[0]);
            }
            $("#data-derival-city").html(data.derival.city);
            $.each(data.derival.terminals, function () {
                $('#data-derival-terminals').append(this.address + '<br>');
            });
            $("#data-arrrival-city").html(data.arrival.city);
            $.each(data.arrival.terminals, function () {
                $('#data-arrival-terminals').append(this.address + '<br>');
            });
            $("#data-price").html(data.price);
            $("#data-air-price").html(data.price);
            $("#data-time-value").html(data.time.nominative);
            $("#data-order_dates-derrival_from_osp_sender").html(data.order_dates.derrival_from_osp_sender);
            $("#data-order_dates-arrival_to_osp_receiver").html(data.order_dates.arrival_to_osp_receiver);
        }
    });
</script>

views/cladr/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Cladr */

$this->title = 'Update Cladr: ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Cladrs', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id, 'name' => $model->name, 'searchString' => $model->searchString, 'regname' => $model->regname]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="cladr-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/cladr/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Cladr */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Cladrs', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="cladr-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id, 'name' => $model->name, 'searchString' => $model->searchString, 'regname' => $model->regname], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id, 'name' => $model->name, 'searchString' => $model->searchString, 'regname' => $model->regname], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'cityID',
            'name',
            'code',
            'searchString',
            'regname',
            'regcode',
            'zonname',
            'zoncode',
        ],
    ]) ?>

</div>